# Generated by Django 3.2.9 on 2021-11-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_credit', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['course_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('school_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_capacity', models.IntegerField()),
            ],
            options={
                'ordering': ['room_id'],
            },
        ),
        migrations.CreateModel(
            name='OfferedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section', models.IntegerField()),
                ('course_capacity', models.IntegerField()),
                ('course_enrolled', models.IntegerField()),
                ('semester_name', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.course')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.room')),
            ],
            options={
                'ordering': ['course', 'course_section', 'semester_name', 'year'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department'),
        ),
    ]
