# Generated by Django 3.2.9 on 2021-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_course_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.IntegerField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_id']},
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='offeredcourses',
            table='offered_courses',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
