# Generated by Django 3.2.9 on 2021-11-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20211120_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['semester_id']},
        ),
        migrations.AlterModelTable(
            name='semester',
            table='semester',
        ),
    ]
