# Generated by Django 3.2.9 on 2021-11-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20211120_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeredcourses',
            options={'ordering': ['course', 'course_section', 'semester', 'year']},
        ),
        migrations.RemoveField(
            model_name='offeredcourses',
            name='semester_name',
        ),
        migrations.AddField(
            model_name='offeredcourses',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.semester'),
        ),
    ]
