# Generated by Django 3.2.9 on 2021-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20211120_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
