# Generated by Django 3.2.9 on 2021-11-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_semester_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offeredcourses',
            options={'ordering': ['course', 'course_section', 'semester']},
        ),
        migrations.RemoveField(
            model_name='offeredcourses',
            name='year',
        ),
    ]
